name: Update Caddy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: prepare git
      run: |
        git config --global user.name "hacky·day"
        git config --global user.email "hacky-day@lkiesow.de"

    - name: prepare github ssh key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        install -dm 700 ~/.ssh/
        echo "${DEPLOY_KEY}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: clone repository
      run: git clone git@github.com:hacky-day/caddy-cloudflare.git ~/caddy-cloudflare-clone

    - name: update Dockerfile
      run: |
        cd ~/caddy-cloudflare-clone
        ./update-caddy-version.sh
